name: "deploy version"
env:
  DOTNET_VERSION: '6.0.x'           # set this to the dot net version to use
  AZURE_WEBAPP_NAME: 'AutoBlocklyApp'
on:
  push:    
    tags:
      - "v*"
  
  workflow_dispatch:

jobs:
  buildHTML:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: put version
      run: |
        echo "${{github.ref_name}}" 
        echo "${{github.ref_name}}" > version.txt


    - name: npm install
      run: |
        cd src        
        cd react_new_app
        cd my-app
        npm i -g npm@8.1.0               
        npm i  
        npm run build
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: releaseBlocklyAutomation
        path: 'src/react_new_app/my-app/build/*'
        retention-days: 1

    - name: verify exists
      run: |
        ls -l ${{github.workspace}}/src/react_new_app/my-app/build/      

    - name: Archive Release 
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'releaseBlocklyAutomation.zip'
        path: '${{github.workspace}}/src/react_new_app/my-app/build/*'
        directory: '${{github.workspace}}/src/react_new_app/my-app/build/'
        exclusions: '*.git* /*node_modules/* .editorconfig'       

    - name: copy release 
      run: |
        find ${{github.workspace}} -type f -name "*.zip"



    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files:  |
            ${{github.workspace}}/src/react_new_app/my-app/build/releaseBlocklyAutomation.zip
            version.txt
        # tag: v${{ env.GITHUB_SHA }}
        #tag_name: v${{ env.GITHUB_SHA }}




    - name: delete older-releases@v0
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        #repo: <owner>/<repoName> # defaults to current repo
        keep_latest: 2
        #delete_tag_pattern: beta # defaults to ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
