name: Build nuget dotnet programmer all

on:
  push:
    # branches:
    #   - main
    tags:
      - "vProgrammerAll*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [16.13.0]

    steps:
      - uses: actions/checkout@v2

      # - name: Node ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}
      # - name: Download  main
      #   id: download-artifact
      #   uses: dawidd6/action-download-artifact@v2
      #   with:
      #     github_token: ${{secrets.GITHUB_TOKEN}}
      #     workflow: deployVersion.yml
      #     name: releaseBlocklyAutomation
      #     workflow_conclusion: success          
      #     path: ${{github.workspace}}/src/Local/LocalAPI/LocalAPI/wwwroot/BlocklyAutomation
      #     if_no_artifact_found: fail

      - name: Download artifact docs local api
        id: download-artifact-docs-localAPI
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: deployVersion.yml
          name: releaseBlocklyAutomation
          workflow_conclusion: success
          path: ${{github.workspace}}/src/Local/LocalAPI/LocalAPI/wwwroot/BlocklyAutomation/help/
          if_no_artifact_found: fail

      - name: verify exists
        run: |
          ls -l ${{github.workspace}}/src/Local/LocalAPI/LocalAPI/wwwroot                
          ls -l ${{github.workspace}}/src/Local/LocalAPI/LocalAPI/wwwroot/BlocklyAutomation      


      - name: Set up .NET Core 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
          include-prerelease: false

      - name: Set up .NET Core 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
          include-prerelease: false

      
      - name: Set up .NET Core 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
          include-prerelease: false

      
      - name: Build with dotnet
        run: |
          cd src
          cd Local
          cd LocalAPI
          dotnet tool restore
          dotnet r buildPack
      
      - name: Upload nuget
        uses: actions/upload-artifact@v2
        with:
          name: programmerAll
          path: ${{github.workspace}}/src/Local/LocalAPI/PACK/
      
      - name: push to nuget
        run: |
          dotnet nuget push ${{github.workspace}}/src/Local/LocalAPI/PACK/progr*symb*.*pkg --api-key  ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json

  