name: "Deploy release"
# env:
  # DOTNET_VERSION: '6.0.x'           # set this to the dot net version to use
  # AZURE_WEBAPP_NAME: 'AutoBlocklyApp'
on:
  push:    
    tags:
      - "vRelease*"
  
  workflow_dispatch:

jobs:
  buildHTML:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.9.0]

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'
        # cache-dependency-path: |
        #   '**/package-lock.json'
        #   '**/package.json'
          

    # - name: put version
    #   run: |
    #     echo "${{github.ref_name}}" 
    #     echo "${{github.ref_name}}" > version.txt

    - name: npm install main blockly
      run: |
        cd src        
        cd blockly10
        npm i  

    - name: build docs main blockly
      run: |
        cd src        
        cd blockly10
        npm i  
        npm run build      


    - name: copy  docs to BlocklyMain
      run: |
        cp -R src/blockly10/build/*  src/react_new_app/my-app/public/help/
          

    - name: build with root 
      run: |
        cd src        
        cd blockly10
        rm public/version.txt
        echo "${{github.ref_name}}" > public/version.txt
        npm run build


    # - name: verify exists app
    #   run: |
    #     echo 'main workspace'
    #     ls -l ${{github.workspace}}/src/react_new_app/my-app/build/      


    - name: Archive production artifacts main
      uses: actions/upload-artifact@v4
      with:
        name: releaseBlocklyAutomation
        path: 'src/blockly10/build/*'
        retention-days: 3
        
    
    - name: ReleaseLocalAPI
      uses: softprops/action-gh-release@v1
      with:
        body: "Latest Release for Manual Install"
        generate_release_notes: true
        draft: false
        prerelease: false
        files:  |
            ${{github.workspace}}/src/blockly10/build/releaseBlocklyAutomation.zip
            version.txt



    - name: delete older-releases@v0
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        #repo: <owner>/<repoName> # defaults to current repo
        keep_latest: 4
        #delete_tag_pattern: beta # defaults to ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
